name: gridbounds
version: '0.0.0.1'
license: MIT
license-file: LICENSE
maintainer: firas@zaidan.de
stability: stable
github: zaidan/gridbounds
synopsis: Collision detection for GridBox
description: >
    This package adds collision detection to GridBox. It is based on
    Earclipper and GJK.
category: Graphics
author:
  - Firas Zaidan
extra-source-files:
  - README.md

ghc-options: -Wall

default-extensions:
  - BangPatterns
  - DeriveFunctor
  - FlexibleContexts
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - ViewPatterns

dependencies:
  - base       >= 4.9 && < 5.0
  - gridbox    >= 0.3 && < 0.4
  - earclipper >= 0.0 && < 0.1
  - gjk        >= 0.0 && < 0.1

library:
  source-dirs: src
  dependencies: []

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - gridbounds
      - hspec
